// {
// 	exercise: 'What is cookie ?',
// 	exerciseAnswer: 'A cookie is a small piece of data that a website stores on a user's browser when they visit the site. ',
// 	explanation: 'Файл cookie — це невеликий фрагмент даних, який веб-сайт зберігає у браузері користувача, коли він відвідує сайт.',
// },

export const id1 = [
	// {
	// 	id: '001qwqw',
	// 	level: 'Intermediate',
	// 	topic: ['JavaScript Basics'],
	// 	category: ['Variables'],
	// 	exerciseType: 'Translate',
	// 	exercise: 'What is cookie ?',
	// 	exerciseAnswer: `A cookie is a small piece of data that a website stores on a user's browser when they visit the site.`,
	// 	explanation:
	// 		'Файл cookie — це невеликий фрагмент даних, який веб-сайт зберігає у браузері користувача, коли він відвідує сайт.',
	// },
	{
		id: '001',
		exercise: 'змінна',
		exerciseAnswer: 'variable',
		explanation: 'A storage location that holds a value.',
		level: 'Intermediate',
		topic: ['JavaScript Basics'],
		category: ['Variables'],
		exerciseType: 'Translate',
	},
	{
		id: '002',
		exercise: 'функція',
		exerciseAnswer: 'function',
		explanation: 'A block of reusable code that performs a task.',
		level: 'Intermediate',
		topic: ['JavaScript Basics'],
		category: ['Functions'],
		exerciseType: 'Translate',
	},
	// {
	// 	id: '003',
	// 	exercise: 'обʼєкт',
	// 	exerciseAnswer: 'object',
	// 	explanation: 'A data structure that stores key-value pairs.',
	// 	level: 'Intermediate',
	// 	topic: ['JavaScript Basics'],
	// 	category: ['Objects'],
	// 	exerciseType: 'Translate',
	// },
	// {
	// 	id: '004',
	// 	exercise: 'цикли',
	// 	exerciseAnswer: 'loops',
	// 	explanation: 'A structure that repeats a block of code.',
	// 	level: 'Intermediate',
	// 	topic: ['JavaScript Basics'],
	// 	category: ['Arrays'],
	// 	exerciseType: 'Translate',
	// },
	// {
	// 	id: '005',
	// 	exercise: 'асинхронність',
	// 	exerciseAnswer: 'asynchrony',
	// 	explanation: 'Execution that does not block the main thread.',
	// 	level: 'Intermediate',
	// 	topic: ['JavaScript Basics'],
	// 	category: ['Control Flow'],
	// 	exerciseType: 'Translate',
	// },
	// {
	// 	id: '006',
	// 	exercise: 'колбек',
	// 	exerciseAnswer: 'callback',
	// 	explanation: 'A function passed as an argument to another function.',
	// 	level: 'Intermediate',
	// 	topic: ['JavaScript Basics'],
	// 	category: ['Loops'],
	// 	exerciseType: 'Translate',
	// },
	// {
	// 	id: '007',
	// 	exercise: 'асинхронность',
	// 	exerciseAnswer: 'asynchrony',
	// 	explanation: 'Execution that does not block the main thread.',
	// 	level: 'Advanced',
	// 	topic: ['JavaScript Advanced'],
	// 	category: ['Asynchronous Programming'],
	// 	exerciseType: 'Translate',
	// },
	// {
	// 	id: '008',
	// 	exercise: 'колбэк',
	// 	exerciseAnswer: 'callback',
	// 	explanation: 'A function passed as an argument to another function.',
	// 	level: 'Intermediate',
	// 	topic: ['JavaScript Advanced'],
	// 	category: ['Callbacks'],
	// 	exerciseType: 'Translate',
	// },
	// {
	// 	id: '009',
	// 	exercise: 'проміс',
	// 	exerciseAnswer: 'promise',
	// 	explanation: 'An object representing the eventual completion of an async operation.',
	// 	level: 'Advanced',
	// 	topic: ['JavaScript Advanced'],
	// 	category: ['Promises'],
	// 	exerciseType: 'Translate',
	// },
	// {
	// 	id: '010',
	// 	exercise: 'замикання',
	// 	exerciseAnswer: 'closure',
	// 	explanation: 'A function that remembers variables from its lexical scope.',
	// 	level: 'Advanced',
	// 	topic: ['JavaScript Advanced'],
	// 	category: ['Closures'],
	// 	exerciseType: 'Translate',
	// },
];

export const id2 = [
	{
		id: '003',
		exercise: 'I do not watch',
		exerciseAnswer: 'I was not watching',
		explanation: 'Convert from Present Simple Negative to Past Continuous Negative',
		level: 'Intermediate',
		topic: ['English Grammar'],
		category: ['Present Simple Negative', 'Past Continuous Negative'],
		exerciseType: 'Converting',
	},
	{
		id: '004',
		exercise: 'The train leaves',
		exerciseAnswer: 'The train left',
		explanation: 'Convert from Present Simple to Past Simple',
		level: 'Intermediate',
		topic: ['English Grammar'],
		category: ['Present Simple', 'Past Simple'],
		exerciseType: 'Converting',
	},
];

export const id3 = [
	{
		id: '3005',
		exercise: 'Why are you',
		exerciseAnswer: 'Why were you',
		explanation: 'Convert from Present Continuous Question to Past Continuous Question',
		level: 'Intermediate',
		topic: ['English Grammar'],
		category: ['Present Continuous', 'Past Continuous'],
		exerciseType: 'Converting',
	},
];
