// {
// 	exercise: 'What is cookie ?',
// 	exerciseAnswer: 'A cookie is a small piece of data that a website stores on a user's browser when they visit the site. ',
// 	explanation: 'Файл cookie — це невеликий фрагмент даних, який веб-сайт зберігає у браузері користувача, коли він відвідує сайт.',
// },

export const id1 = [
	{
		exercise: 'ітератор',
		exerciseAnswer: 'iterator',
		explanation: 'An object that allows sequential access to elements in a collection.',
		id: 'f4a878a6-0c96-4286-be14-dce2386d772a',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'генератор',
		exerciseAnswer: 'generator',
		explanation: 'A function that can be paused and resumed, using `yield`.',
		id: '9b879282-8f38-41c4-965b-2c579ab7f57f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'синтаксичний цукор',
		exerciseAnswer: 'syntactic sugar',
		explanation: 'A syntax that makes code easier to read but does not add new functionality.',
		id: 'e79f4b4d-55f6-4921-bd5e-43185ebc3e90',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'DOM',
		exerciseAnswer: 'DOM',
		explanation: 'The Document Object Model, representing the structure of a webpage.',
		id: '6012f571-5c29-44e3-8133-c0d72235cc3b',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'маніпуляція DOM',
		exerciseAnswer: 'DOM manipulation',
		explanation: 'Changing the structure, content, or style of a webpage using JavaScript.',
		id: '7c0c743e-d85c-42ba-adf3-b871798fd6af',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'вузол',
		exerciseAnswer: 'node',
		explanation: 'An individual part of the DOM, such as an element or text.',
		id: '9d986680-834d-4b5a-9e09-40442dfa081f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'елемент',
		exerciseAnswer: 'element',
		explanation: 'A specific type of node representing an HTML element.',
		id: 'd25f78ad-4675-4f8b-a776-55819e6ffd27',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'атрибут',
		exerciseAnswer: 'attribute',
		explanation: 'A property of an HTML element that provides additional information.',
		id: '9709463b-0b0c-42f4-ab56-872070a6381e',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'CSS-клас',
		exerciseAnswer: 'CSS class',
		explanation: 'A way to apply styles to multiple elements using a shared name.',
		id: '195734d8-59ad-43c5-9cd9-a8165b18b74f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'ідентифікатор',
		exerciseAnswer: 'id',
		explanation: 'A unique identifier assigned to an HTML element.',
		id: 'c350b068-4858-4301-9d50-cb3971e76e47',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'перехоплювач подій',
		exerciseAnswer: 'event listener',
		explanation: 'A function that listens for and responds to events on an element.',
		id: '14051a00-7910-4ba7-ade1-74b326d4e340',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'preventDefault',
		exerciseAnswer: 'preventDefault',
		explanation: 'A method that prevents the default behavior of an event.',
		id: 'a52fc5b3-a715-4051-a27e-c3cec018260e',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'stopPropagation',
		exerciseAnswer: 'stopPropagation',
		explanation: 'A method that stops an event from bubbling up the DOM tree.',
		id: '56133caf-4ba2-482a-a014-3d5ad8b3461a',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'fetch',
		exerciseAnswer: 'fetch',
		explanation: 'A function used to make HTTP requests in JavaScript.',
		id: '4821c5d1-f706-40b3-b3cc-9afe9ca9de1f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'API',
		exerciseAnswer: 'API',
		explanation:
			'A set of functions that allow communication between different software components.',
		id: '87c7fc81-e6a9-43e2-b0f1-0f5f5ff4bc55',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'REST API',
		exerciseAnswer: 'REST API',
		explanation: 'An API that follows Representational State Transfer principles.',
		id: '143abfe4-e5d8-47b0-afd1-1ebd64cc5110',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'WebSocket',
		exerciseAnswer: 'WebSocket',
		explanation: 'A protocol that provides full-duplex communication between client and server.',
		id: '01862606-c039-4349-96df-7a8e26cc95bb',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'AJAX',
		exerciseAnswer: 'AJAX',
		explanation: 'A technique for updating web pages asynchronously without reloading them.',
		id: 'e4e4f45c-b82b-4d28-be22-969d04677806',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'CORS',
		exerciseAnswer: 'CORS',
		explanation: 'Cross-Origin Resource Sharing, a mechanism for handling cross-site requests.',
		id: '958d687a-bb06-4b9f-b0e3-7891ca267707',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'XHR',
		exerciseAnswer: 'XHR',
		explanation: 'XMLHttpRequest, an older way to make HTTP requests in JavaScript.',
		id: 'c3791e83-cdb0-4c32-b25f-5eec56bdb61f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'сервер',
		exerciseAnswer: 'server',
		explanation: 'A computer or system that provides resources or services to clients.',
		id: 'f44b2153-a923-4e06-924d-a5ad13902b8f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'клієнт',
		exerciseAnswer: 'client',
		explanation: 'A device or application that accesses services from a server.',
		id: '47fe5c43-13ca-4ef8-88c7-7720f9c2e6c5',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'однопотоковість',
		exerciseAnswer: 'single-threaded',
		explanation: 'JavaScript runs in a single-threaded environment, processing one task at a time.',
		id: 'a0a3194c-14b5-4e27-8d13-74b4e6d22926',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'подвійний виклик',
		exerciseAnswer: 'debounce',
		explanation: 'A technique that limits how often a function executes.',
		id: '0bde9118-7b44-4910-9a34-6f1c3c1a6fa5',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'тротлінг',
		exerciseAnswer: 'throttling',
		explanation:
			'A technique that ensures a function executes at most once in a given time period.',
		id: 'a46229f9-7c31-41d9-b804-500bd08d639b',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'this',
		exerciseAnswer: 'this',
		explanation: 'A keyword that refers to the object that a function is called on.',
		id: '995b0fa8-ed66-4e61-a7b8-07460e9a5a6e',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'apply',
		exerciseAnswer: 'apply',
		explanation:
			'A method that calls a function with a specified `this` value and arguments as an array.',
		id: '05db7415-6d5d-4b51-8057-39f80f08f381',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'call',
		exerciseAnswer: 'call',
		explanation:
			'A method that calls a function with a specified `this` value and individual arguments.',
		id: '74ee18af-d5db-4f94-8df4-09c420081401',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'bind',
		exerciseAnswer: 'bind',
		explanation: 'A method that returns a new function with `this` set to a specific value.',
		id: 'a4eeb565-3588-417d-99e1-2dcd6f86a442',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'клас',
		exerciseAnswer: 'class',
		explanation: 'A blueprint for creating objects with shared properties and methods.',
		id: '18684f8e-4179-44f6-aedd-c19ac597499c',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'екземпляр',
		exerciseAnswer: 'instance',
		explanation: 'An object created from a class.',
		id: 'cf565583-0828-46eb-b160-9381e4b05b94',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'наслідування',
		exerciseAnswer: 'inheritance',
		explanation: 'A mechanism where one class derives properties and methods from another.',
		id: 'd37ef379-75e6-4780-adb7-7eb21908255f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'поліморфізм',
		exerciseAnswer: 'polymorphism',
		explanation:
			'A concept where a function or method behaves differently based on the object calling it.',
		id: 'e7576177-e3db-48fd-8b0f-8e5bbebfa6f3',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'інкапсуляція',
		exerciseAnswer: 'encapsulation',
		explanation: 'The practice of restricting direct access to object properties and methods.',
		id: 'd8901cc4-4d8e-433c-b45a-f1b62a6ec115',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'абстракція',
		exerciseAnswer: 'abstraction',
		explanation: 'Hiding complex implementation details and exposing only essential features.',
		id: '94cadb95-d210-4e20-bacf-fbc7bc014809',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'прототип',
		exerciseAnswer: 'prototype',
		explanation: 'An object from which other objects inherit properties and methods.',
		id: '1e7b7dce-cd2a-4dad-8fc6-84fc90001a1b',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'ланцюжок прототипів',
		exerciseAnswer: 'prototype chain',
		explanation: 'A system in JavaScript where objects inherit from other objects via prototypes.',
		id: '00401ed6-1d06-45e6-a1fd-27f10f35eaf4',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'глибоке копіювання',
		exerciseAnswer: 'deep copy',
		explanation: 'A copy of an object where nested objects are also duplicated.',
		id: '6c14cec7-aa0b-4bfc-9a60-f707776f9ce1',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'поверхневе копіювання',
		exerciseAnswer: 'shallow copy',
		explanation: 'A copy of an object where nested objects are referenced, not duplicated.',
		id: '6e095041-232a-42b3-9069-c4f4e4d3a1ee',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'стек викликів',
		exerciseAnswer: 'call stack',
		explanation: 'A data structure that keeps track of function execution in JavaScript.',
		id: '5c49d1d7-d84f-42ae-adf8-0e9be44eda80',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'heap',
		exerciseAnswer: 'heap',
		explanation: 'An area of memory where objects are stored dynamically.',
		id: '0b939241-4ae0-44fd-a8a4-d178a24a70db',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'мемоізація',
		exerciseAnswer: 'memoization',
		explanation: 'An optimization technique that caches the results of expensive function calls.',
		id: '68766425-8bcb-44fa-8919-543b1d212b97',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'рекурсія',
		exerciseAnswer: 'recursion',
		explanation: 'A function that calls itself until a base condition is met.',
		id: '5f2a5b71-db63-4bda-946b-c45e578196fb',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'хеш-таблиця',
		exerciseAnswer: 'hash table',
		explanation: 'A data structure that stores key-value pairs using a hash function.',
		id: '76cf39de-bc14-4d74-8b02-cfba7030e6e7',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'глибина виклику',
		exerciseAnswer: 'call depth',
		explanation: 'The number of nested function calls currently on the call stack.',
		id: '82b54e9b-220f-432b-a1d7-cb5b69fd01d2',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'стрім',
		exerciseAnswer: 'stream',
		explanation:
			'A sequence of data that can be processed incrementally rather than loading everything at once.',
		id: '8a9ac00a-7b60-4368-bb24-cd7c3cb7143d',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: "пул з'єднань",
		exerciseAnswer: 'connection pool',
		explanation: 'A collection of reusable database connections to improve performance.',
		id: '7ec57bfb-ca2d-4e4d-be38-b51903e4a995',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'пайплайн',
		exerciseAnswer: 'pipeline',
		explanation: 'A series of functions that process data step by step.',
		id: '8489a9c9-2ebe-48f2-b587-f0db1068940d',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
];

export const id2 = [
	{
		exercise: 'flexbox',
		exerciseAnswer: 'flex-wrap',
		explanation: 'A property that defines whether flex items should wrap onto multiple lines.',
		id: '186884a7-f545-4cd9-b1d5-6e76d4106b3d',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'flexbox',
		exerciseAnswer: 'align-self',
		explanation:
			'A property that allows individual flex items to override the container align-items value.',
		id: 'db43f9c8-0750-4863-bc16-fc9ad8087767',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'grid',
		exerciseAnswer: 'grid-gap',
		explanation: 'A shorthand property for setting the row and column gaps in a grid layout.',
		id: '965f43be-1f07-453f-b5bf-54e5d0005029',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'grid',
		exerciseAnswer: 'grid-auto-flow',
		explanation: 'A property that controls how auto-placed items are inserted into the grid.',
		id: '1cc92bd9-9549-4ffe-b530-9ef786c0bc5f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'grid',
		exerciseAnswer: 'grid-area',
		explanation: 'A property that allows an item to be placed into a specific grid area.',
		id: '5510891e-49ee-4ce1-a5e3-162fc129cd2d',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'units',
		exerciseAnswer: 'rem',
		explanation: 'A relative unit based on the root element font size.',
		id: '27664bcf-4f0c-4c05-ba34-0d690a9f8301',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'units',
		exerciseAnswer: 'vh',
		explanation: 'A unit that represents 1% of the viewport height.',
		id: '02f02898-c819-4f46-b32a-b8e2d7137b9a',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'units',
		exerciseAnswer: '%',
		explanation: 'A unit that defines sizes as a percentage of the containing element.',
		id: 'a5712198-327b-4233-968a-37b82d5dc2c1',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'background',
		exerciseAnswer: 'background-position',
		explanation: 'A property that defines the starting position of a background image.',
		id: '81afe044-3b82-41b8-a813-49493f408d3b',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'background',
		exerciseAnswer: 'background-repeat',
		explanation: 'A property that defines whether a background image should repeat.',
		id: '6b813c78-067c-4bf6-a577-49e6dc642f4f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'background',
		exerciseAnswer: 'background-clip',
		explanation: 'A property that specifies how far a background extends within an element.',
		id: '58e8ce16-a469-4a82-9297-04d3441f323a',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'border',
		exerciseAnswer: 'border-style',
		explanation:
			'A property that defines the style of an element border, such as solid, dashed, or dotted.',
		id: '8dfbafa3-0b3b-4d96-9c7f-c2d1f54652a6',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'border',
		exerciseAnswer: 'border-color',
		explanation: 'A property that sets the color of an element border.',
		id: '7c2de5c0-1ddd-49c5-8292-504875d02ec0',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'border',
		exerciseAnswer: 'outline',
		explanation: 'A property that adds a line around an element, outside the border.',
		id: 'e2413d34-0a9c-4117-a3be-85e3a4fc4b56',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'shadows',
		exerciseAnswer: 'box-shadow',
		explanation: 'A property that applies a shadow to an element box.',
		id: '07748e64-b15a-441b-845e-8fc783a6fd23',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'shadows',
		exerciseAnswer: 'text-shadow',
		explanation: 'A property that applies a shadow effect to text.',
		id: '8958480f-f33d-4e99-afaf-f9f9311ad96d',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'overflow',
		exerciseAnswer: 'overflow-x',
		explanation: 'A property that controls the horizontal overflow behavior of content.',
		id: 'bc826755-68e7-4768-a59d-061c70ecda67',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'overflow',
		exerciseAnswer: 'overflow-y',
		explanation: 'A property that controls the vertical overflow behavior of content.',
		id: '90d360fb-c263-464c-9d3a-5d0546e2abf2',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'opacity',
		exerciseAnswer: 'opacity',
		explanation: 'A property that sets the transparency level of an element.',
		id: '0db1eed5-b98f-4778-a03a-1bc09853cff6',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'transforms',
		exerciseAnswer: 'rotate',
		explanation: 'A transform function that rotates an element.',
		id: '47153cab-93a4-4f67-a13a-66af75a49f58',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'transforms',
		exerciseAnswer: 'scale',
		explanation: 'A transform function that resizes an element.',
		id: 'bb717702-401f-48a8-8df7-204efa927f1f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'transforms',
		exerciseAnswer: 'translate',
		explanation: 'A transform function that moves an element in the X and Y directions.',
		id: 'e566d47f-0bd8-4d7f-81d9-5cdc59b4cff9',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'transforms',
		exerciseAnswer: 'skew',
		explanation: 'A transform function that skews an element along the X or Y axis.',
		id: '3efa88a2-f8ef-43ef-b361-f54b0bb8fd16',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'cursor',
		exerciseAnswer: 'crosshair',
		explanation: 'A cursor style that shows a crosshair pointer.',
		id: 'f7707f9f-57e9-4139-9acc-743108e28a6f',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'cursor',
		exerciseAnswer: 'wait',
		explanation: 'A cursor style that indicates a process is in progress.',
		id: '955985c8-8119-40dd-9c6e-ecfd38c5dfa0',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'visibility',
		exerciseAnswer: 'hidden',
		explanation: 'A visibility value that hides an element but keeps its space in the layout.',
		id: '52017212-7c8b-4827-af29-dbfb765a8aca',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'visibility',
		exerciseAnswer: 'collapse',
		explanation: 'A visibility value that hides table rows or columns, removing their space.',
		id: '99f32fd4-2737-4a9d-bc7c-67bc08874b8d',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'content',
		exerciseAnswer: 'content',
		explanation: 'A property used with pseudo-elements to insert generated content.',
		id: '8231444b-a306-4e5f-a6fd-a914876c28c0',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'list',
		exerciseAnswer: 'list-style-type',
		explanation: 'A property that defines the type of bullet or numbering for a list.',
		id: 'c947a937-0671-40d9-82a4-ccd7badee615',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'list',
		exerciseAnswer: 'list-style-position',
		explanation:
			'A property that defines whether list markers appear inside or outside the content flow.',
		id: 'eb0cac25-cee2-4a36-a7ec-27ada2293dde',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'columns',
		exerciseAnswer: 'column-count',
		explanation:
			'A property that specifies the number of columns an element should be divided into.',
		id: '189724db-621e-40fe-9c97-678d0fb13db1',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'columns',
		exerciseAnswer: 'column-gap',
		explanation: 'A property that sets the gap between columns.',
		id: '00e36f73-4b55-4485-83fb-78daad27ebc5',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'columns',
		exerciseAnswer: 'column-rule',
		explanation: 'A property that sets the width, style, and color of the line between columns.',
		id: '5e0e71c6-f344-4a5f-942e-59bb72b84f8c',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'writing mode',
		exerciseAnswer: 'writing-mode',
		explanation: 'A property that defines the text direction and block flow.',
		id: '3342f3af-afcd-4662-bce2-015679b357d6',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'writing mode',
		exerciseAnswer: 'direction',
		explanation: 'A property that specifies text direction as left-to-right or right-to-left.',
		id: 'ebf09270-880b-4c15-8fae-8914425bf365',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'tables',
		exerciseAnswer: 'border-collapse',
		explanation: 'A property that defines whether table borders should be collapsed or separated.',
		id: '895d4479-792c-4cdf-adf4-7dc58b89b9d0',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'tables',
		exerciseAnswer: 'table-layout',
		explanation: 'A property that controls the algorithm used to lay out table cells.',
		id: '381cf77e-fd31-4de8-b986-f0388f5ff2d7',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'counters',
		exerciseAnswer: 'counter-reset',
		explanation: 'A property that initializes or resets a counter.',
		id: 'd8a09f1c-0801-4fb9-b948-2fcd157b5861',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'counters',
		exerciseAnswer: 'counter-increment',
		explanation: 'A property that increases the value of a counter.',
		id: '342ab92b-ae9b-41f2-b5d9-b7f801dc02b0',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'filters',
		exerciseAnswer: 'blur',
		explanation: 'A filter function that applies a blur effect to an element.',
		id: 'bf6296e8-b628-49b8-9dd0-47362078c910',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'filters',
		exerciseAnswer: 'grayscale',
		explanation: 'A filter function that converts colors to grayscale.',
		id: 'e2792a71-2a01-4b8e-872a-e2cef7958083',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'filters',
		exerciseAnswer: 'brightness',
		explanation: 'A filter function that adjusts the brightness of an element.',
		id: '73874dc0-b976-4ac3-875c-4e83815aa3af',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'filters',
		exerciseAnswer: 'contrast',
		explanation: 'A filter function that adjusts the contrast of an element.',
		id: '7a904b9e-d12c-4d92-8cfc-5903f2b365b3',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'variables',
		exerciseAnswer: 'var()',
		explanation: 'A function that retrieves the value of a CSS variable.',
		id: 'f0952997-d33e-4975-a012-98e038cc9e81',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'variables',
		exerciseAnswer: '--custom-property',
		explanation: 'A syntax for defining a custom CSS variable.',
		id: '6cfef057-ca1d-4f53-a3c6-c95b868c4bd9',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'position',
		exerciseAnswer: 'absolute',
		explanation:
			'A positioning method that places an element relative to its closest positioned ancestor.',
		id: 'cb6cee55-22c9-4d3b-80c4-955289c14e40',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'position',
		exerciseAnswer: 'relative',
		explanation: 'A positioning method that places an element relative to its normal position.',
		id: '7b9ffd9c-6c20-489c-9421-25ab4e9430da',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'position',
		exerciseAnswer: 'fixed',
		explanation:
			'A positioning method that places an element relative to the viewport, staying in the same place even when scrolling.',
		id: 'ab2784a2-2e92-435c-a8d5-1f1318c6bbd1',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'display',
		exerciseAnswer: 'flex',
		explanation:
			'A display value that enables flexbox layout, allowing items to align and distribute space efficiently.',
		id: 'c2f9f223-5a77-497b-91bc-244d14e481f0',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'display',
		exerciseAnswer: 'grid',
		explanation:
			'A display value that enables grid layout, providing a two-dimensional structure for placing items.',
		id: 'c2527e5e-28ff-443a-abf3-492552d487d9',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'flexbox',
		exerciseAnswer: 'justify-content',
		explanation: 'A property that defines how flex items are aligned along the main axis.',
		id: '64a31547-0b0c-43ff-8a75-a8e828233a06',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'flexbox',
		exerciseAnswer: 'align-items',
		explanation: 'A property that defines how flex items are aligned along the cross axis.',
		id: 'ab5c923a-713f-4a33-87bc-db2724ac393e',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'grid',
		exerciseAnswer: 'grid-template-columns',
		explanation: 'A property that defines the number and size of columns in a CSS grid layout.',
		id: '448f9413-522a-4529-bd8d-04087a2f1249',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'grid',
		exerciseAnswer: 'grid-template-rows',
		explanation: 'A property that defines the number and size of rows in a CSS grid layout.',
		id: 'b354c40a-a10e-4e0a-bf82-7f7148761791',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'colors',
		exerciseAnswer: 'rgba',
		explanation:
			'A color model that includes red, green, blue, and an alpha channel for transparency.',
		id: 'b0f7ec3e-bbde-486d-b685-db73be3a0a65',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'typography',
		exerciseAnswer: 'font-family',
		explanation: 'A property that defines the typeface or font used for text.',
		id: 'fb14239d-387b-4816-a5bc-0feb42274275',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'typography',
		exerciseAnswer: 'font-size',
		explanation: 'A property that sets the size of text.',
		id: 'e84f0c05-89e3-4b9a-9c6b-518c729dcd7b',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'typography',
		exerciseAnswer: 'font-weight',
		explanation: 'A property that defines the thickness of characters in text.',
		id: 'f96fde8a-40ff-4f65-8e5d-a0ef6a96f605',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'background',
		exerciseAnswer: 'background-image',
		explanation: 'A property that sets an image as the background of an element.',
		id: '8b50ac8a-5ae8-49ce-94fe-d05e4b6e1242',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'background',
		exerciseAnswer: 'background-size',
		explanation: 'A property that defines the size of a background image.',
		id: 'ca573a2f-364c-465d-9d3d-82d9671f15a0',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'border',
		exerciseAnswer: 'border-radius',
		explanation: 'A property that defines the curvature of an element corners.',
		id: '6348555c-19b3-426a-8f89-4c7165a4afa3',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'border',
		exerciseAnswer: 'border-width',
		explanation: 'A property that defines the thickness of an element border.',
		id: '52439d73-69ba-46fd-81e7-e318a4d57413',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'box model',
		exerciseAnswer: 'margin',
		explanation: 'A property that defines the outer space around an element.',
		id: '345fc9b7-05bc-4f9d-be84-b11f7bc559f5',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'box model',
		exerciseAnswer: 'padding',
		explanation:
			'A property that defines the inner space between an element content and its border.',
		id: '1a4e6338-a730-458a-9ed4-0e0b16139757',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'box model',
		exerciseAnswer: 'box-sizing',
		explanation:
			'A property that defines how the total width and height of an element are calculated.',
		id: '559b5767-7067-4521-ae7d-f1e5fecf7302',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'animations',
		exerciseAnswer: 'transition',
		explanation: 'A property that defines the speed and effect of property changes.',
		id: '6f305dfa-1b06-48c1-800f-1b7cd0512765',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'animations',
		exerciseAnswer: 'animation',
		explanation: 'A property that allows elements to move or change over time.',
		id: '096e9873-3911-4937-b987-e10c636a7743',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'animations',
		exerciseAnswer: 'animation-duration',
		explanation:
			'A property that defines the length of time an animation takes to complete one cycle.',
		id: 'c8b26e0d-7554-4ac2-b009-306c8378fa19',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'animations',
		exerciseAnswer: 'animation-timing-function',
		explanation: 'A property that defines the speed curve of an animation.',
		id: 'b2751e3a-045e-442d-a964-924215f32eb2',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'visibility',
		exerciseAnswer: 'opacity',
		explanation: 'A property that defines the transparency level of an element.',
		id: '611b6f68-1abc-4350-9e78-4bbf3404adf2',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'visibility',
		exerciseAnswer: 'visibility',
		explanation: 'A property that controls whether an element is visible without affecting layout.',
		id: '93fd4068-d176-4d78-88d4-2206fadc4163',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'cursor',
		exerciseAnswer: 'pointer',
		explanation: 'A cursor value that changes the pointer to indicate a clickable element.',
		id: 'baee04ae-0d4b-4999-915b-a7a5660d1d56',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'cursor',
		exerciseAnswer: 'not-allowed',
		explanation: 'A cursor value that indicates an action is not allowed.',
		id: '705608c6-d467-4ff1-b41c-393caf9c6884',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'pseudo-elements',
		exerciseAnswer: '::before',
		explanation: 'A pseudo-element that inserts content before an element actual content.',
		id: '8fb675dd-f41d-4a77-910d-d12a1f88cc80',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'pseudo-elements',
		exerciseAnswer: '::after',
		explanation: 'A pseudo-element that inserts content after an element actual content.',
		id: '93070739-0b63-4f49-b542-af835529882b',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'pseudo-classes',
		exerciseAnswer: ':hover',
		explanation: 'A pseudo-class that applies styles when an element is hovered over.',
		id: 'b3d45164-352d-4551-9789-f9216e17e7c2',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
	{
		exercise: 'pseudo-classes',
		exerciseAnswer: ':nth-child',
		explanation:
			'A pseudo-class that selects elements based on their position in a parent container.',
		id: '87ec21fe-03bf-40bd-adf1-b1641fefbfbe',
		level: 'Intermediate',
		topic: ['JavaScript Intermediate'],
		category: ['JavaScript'],
		exerciseType: 'Translate',
	},
];

export const id3 = [
	{
		id: '3005',
		exercise: 'flexbox',
		exerciseAnswer: 'A CSS layout model',
		explanation:
			'A layout model that provides an efficient way to align and distribute space among items in a container.',
		level: 'Intermediate',
		topic: ['English Grammar'],
		category: ['Present Continuous', 'Past Continuous'],
		exerciseType: 'Converting',
	},
];
