name: Check tsc
run-name: ${{ github.actor }}
on:
  push:
    branches: [master, develop]
jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
